spring:
  mail:
    host: smtp.gmail.com
    username: ahmaddamha680@gmail.com
    password: uywvthfqllguykgc
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true