
server:
  port: 8887
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true

    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE